const L=(title,body,parts,region='body',margin=1.22)=>({title,body,parts,region,margin});

export const lessons={
 circulation:{
  icon:'♥',system:'circulatory',title:['วงจรเลือด','Circulation'],start:['เปิดบทเรียนระบบไหลเวียนเลือด','Start circulation lesson'],simulation:{heart:true,blood:true,lungs:true,gut:false,air:false,urine:false,signal:false},
  steps:[
   {id:'overview',...L(['ภาพรวมวงจรเลือด','Circulation overview'],['เลือดไหลเป็นวงจรต่อเนื่อง: ร่างกาย → หัวใจขวา → ปอด → หัวใจซ้าย → ร่างกาย','Blood circulates continuously: body → right heart → lungs → left heart → body.'],['heart','vena-cava','pulmonary-artery--1','pulmonary-artery-1','lung-left','lung-right','pulmonary-vein--1','pulmonary-vein-1','aorta'],'chest',1.2)},
   {id:'venous-return',...L(['1 · เลือดกลับเข้าสู่หัวใจ','1 · Venous return to the heart'],['เลือดที่ใช้ออกซิเจนแล้วจากศีรษะ แขน ไต ตับ และขา ไหลกลับผ่านหลอดเลือดดำและ venae cavae เข้าสู่หัวใจด้านขวา','Deoxygenated blood from the head, arms, kidneys, liver and legs returns through veins and the venae cavae to the right side of the heart.'],['heart','vena-cava','jugular-vein--1','jugular-vein-1','brachial-vein--1','brachial-vein-1','renal-vein--1','renal-vein-1','hepatic-vein','femoral-vein--1','femoral-vein-1'],'body',1.1)},
   {id:'right-heart',...L(['2 · หัวใจขวาส่งเลือดไปปอด','2 · Right heart sends blood to the lungs'],['หัวใจห้องล่างขวาบีบเลือดที่มีออกซิเจนต่ำออกทางหลอดเลือดแดงปอดไปยังปอดทั้งสองข้าง','The right ventricle pumps oxygen-poor blood through the pulmonary arteries to both lungs.'],['heart','pulmonary-artery--1','pulmonary-artery-1','lung-left','lung-right'],'chest',1.35)},
   {id:'gas-exchange',...L(['3 · แลกเปลี่ยนแก๊สที่ปอด','3 · Gas exchange in the lungs'],['ที่ถุงลม เลือดรับออกซิเจนและปล่อยคาร์บอนไดออกไซด์ จากนั้นจึงกลายเป็นเลือดที่มีออกซิเจนมากขึ้น','At the alveoli, blood takes up oxygen and releases carbon dioxide, becoming oxygen-rich.'],['lung-left','lung-right','pulmonary-artery--1','pulmonary-artery-1','pulmonary-vein--1','pulmonary-vein-1'],'chest',1.45)},
   {id:'left-heart',...L(['4 · เลือดกลับหัวใจซ้าย','4 · Oxygenated blood returns to the left heart'],['เลือดที่มีออกซิเจนไหลกลับทางหลอดเลือดดำปอด เข้าหัวใจด้านซ้าย เพื่อเตรียมส่งออกสู่ร่างกาย','Oxygenated blood returns through the pulmonary veins to the left side of the heart, ready for systemic circulation.'],['heart','pulmonary-vein--1','pulmonary-vein-1'],'chest',1.55)},
   {id:'systemic-outflow',...L(['5 · ส่งเลือดไปทั่วร่างกาย','5 · Systemic arterial outflow'],['หัวใจห้องล่างซ้ายส่งเลือดผ่าน aorta แล้วแยกไปยังศีรษะ แขน ไต ตับ เชิงกราน และขา','The left ventricle sends blood through the aorta, which branches to the head, arms, kidneys, liver, pelvis and legs.'],['heart','aorta','carotid-artery--1','carotid-artery-1','brachial-artery--1','brachial-artery-1','renal-artery--1','renal-artery-1','hepatic-artery','femoral-artery--1','femoral-artery-1'],'body',1.08)},
   {id:'portal',...L(['6 · เส้นทางพิเศษจากลำไส้สู่ตับ','6 · Special portal route from gut to liver'],['เลือดที่รับสารอาหารจากทางเดินอาหารจะผ่าน hepatic portal vein ไปยังตับก่อน แล้วจึงไหลกลับสู่ระบบหลอดเลือดดำใหญ่','Nutrient-rich blood from the digestive tract travels through the hepatic portal vein to the liver before returning to systemic venous circulation.'],['small-intestine','large-intestine','liver','portal-vein','hepatic-vein'],'abdomen',1.4)},
   {id:'complete-cycle',...L(['7 · วงจรสมบูรณ์','7 · Complete circulation cycle'],['เมื่อเลือดไหลกลับสู่หัวใจด้านขวา วงจรจะเริ่มซ้ำอีกครั้งอย่างต่อเนื่องตลอดเวลา','When blood returns to the right side of the heart, the cycle repeats continuously.'],['heart','vena-cava','pulmonary-artery--1','pulmonary-artery-1','lung-left','lung-right','pulmonary-vein--1','pulmonary-vein-1','aorta','carotid-artery--1','carotid-artery-1','brachial-artery--1','brachial-artery-1','renal-artery--1','renal-artery-1','hepatic-artery','hepatic-vein','portal-vein','femoral-artery--1','femoral-artery-1','jugular-vein--1','jugular-vein-1','brachial-vein--1','brachial-vein-1','renal-vein--1','renal-vein-1','femoral-vein--1','femoral-vein-1'],'body',1.06)}
  ]
 },
 respiratory:{
  icon:'◡',system:'respiratory',title:['ระบบหายใจ','Respiration'],start:['เปิดบทเรียนระบบหายใจ','Start respiratory lesson'],simulation:{heart:false,blood:false,lungs:true,gut:false,air:true,urine:false,signal:false},
  steps:[
   {id:'air-entry',...L(['1 · อากาศเข้าสู่ร่างกาย','1 · Air enters the respiratory tract'],['อากาศเข้าสู่โพรงจมูก ซึ่งช่วยกรอง อุ่น และเพิ่มความชื้นก่อนผ่านลงสู่ทางเดินหายใจ','Air enters the nasal cavity, where it is filtered, warmed and humidified before moving deeper into the airway.'],['nasal-cavity','larynx','trachea'],'head',1.32)},
   {id:'trachea',...L(['2 · ผ่านกล่องเสียงและหลอดลมคอ','2 · Through the larynx and trachea'],['อากาศผ่านกล่องเสียงลงสู่ trachea ซึ่งมีวงกระดูกอ่อนช่วยพยุงทางเดินอากาศให้เปิดอยู่','Air passes the larynx into the trachea, whose cartilage rings help keep the airway open.'],['larynx','trachea'],'chest',1.5)},
   {id:'bronchi',...L(['3 · แยกเข้าสู่หลอดลมซ้าย–ขวา','3 · Air divides into the main bronchi'],['ปลาย trachea แยกเป็นหลอดลมใหญ่ซ้ายและขวา แล้วแตกแขนงเข้าสู่เนื้อปอด','The trachea divides into the left and right main bronchi, which branch through the lungs.'],['trachea','bronchus--1','bronchus-1','lung-left','lung-right'],'chest',1.38)},
   {id:'inhalation',...L(['4 · หายใจเข้า','4 · Inhalation'],['กะบังลมหดตัวและเคลื่อนต่ำลง ช่องอกขยาย ทำให้ปอดขยายและอากาศไหลเข้า','The diaphragm contracts and moves downward; the thoracic cavity expands, the lungs enlarge and air flows inward.'],['lung-left','lung-right','diaphragm'],'chest',1.35)},
   {id:'alveoli',...L(['5 · แลกเปลี่ยนแก๊ส','5 · Gas exchange'],['ในถุงลม ออกซิเจนแพร่เข้าสู่เลือด ขณะที่คาร์บอนไดออกไซด์แพร่ออกจากเลือดเข้าสู่อากาศในถุงลม','In the alveoli, oxygen diffuses into blood while carbon dioxide diffuses from blood into alveolar air.'],['lung-left','lung-right','pulmonary-artery--1','pulmonary-artery-1','pulmonary-vein--1','pulmonary-vein-1'],'chest',1.45)},
   {id:'exhalation',...L(['6 · หายใจออก','6 · Exhalation'],['เมื่อกะบังลมคลายตัว ช่องอกมีขนาดลดลง ปอดคืนรูปและดันอากาศออกตามทางเดิม','As the diaphragm relaxes, thoracic volume decreases and elastic recoil moves air back out through the same airway.'],['lung-left','lung-right','diaphragm','bronchus--1','bronchus-1','trachea'],'chest',1.32)}
  ]
 },
 digestive:{
  icon:'◈',system:'digestive',title:['ระบบย่อยอาหาร','Digestion'],start:['เปิดบทเรียนระบบย่อยอาหาร','Start digestive lesson'],simulation:{heart:false,blood:false,lungs:false,gut:true,air:false,urine:false,signal:false},
  steps:[
   {id:'mouth',...L(['1 · เริ่มต้นที่ปากและลิ้น','1 · Digestion begins in the mouth'],['ลิ้นช่วยคลุกเคล้าอาหารกับน้ำลาย จัดก้อนอาหาร และผลักอาหารเข้าสู่กระบวนการกลืน','The tongue mixes food with saliva, shapes the bolus and helps move it into the swallowing pathway.'],['tongue','esophagus'],'head',1.4)},
   {id:'esophagus',...L(['2 · หลอดอาหารลำเลียงอาหาร','2 · The esophagus moves food'],['กล้ามเนื้อผนังหลอดอาหารบีบตัวเป็นคลื่น หรือ peristalsis เพื่อส่งอาหารลงสู่กระเพาะ','Wave-like peristaltic contractions of the esophagus move swallowed food toward the stomach.'],['esophagus','stomach'],'chest',1.42)},
   {id:'stomach',...L(['3 · กระเพาะย่อยและคลุกเคล้า','3 · Stomach mixing and digestion'],['กระเพาะบีบคลุกอาหารกับกรดและเอนไซม์ ช่วยเริ่มย่อยโปรตีนและเปลี่ยนอาหารเป็นของเหลวกึ่งข้น','The stomach churns food with acid and enzymes, beginning protein digestion and forming semi-fluid chyme.'],['stomach'],'abdomen',1.65)},
   {id:'accessory',...L(['4 · ตับ ถุงน้ำดี และตับอ่อนช่วยย่อย','4 · Liver, gallbladder and pancreas assist digestion'],['ตับสร้างน้ำดี ถุงน้ำดีเก็บน้ำดี และตับอ่อนส่งเอนไซม์กับไบคาร์บอเนตเข้าสู่ลำไส้เล็ก','The liver makes bile, the gallbladder stores it, and the pancreas provides digestive enzymes and bicarbonate to the small intestine.'],['liver','gallbladder','pancreas','duodenum','small-intestine'],'abdomen',1.35)},
   {id:'small-intestine',...L(['5 · ลำไส้เล็กย่อยและดูดซึม','5 · Small-intestinal digestion and absorption'],['duodenum, jejunum และ ileum ทำหน้าที่ย่อยต่อและดูดซึมสารอาหารส่วนใหญ่เข้าสู่ระบบไหลเวียน','The duodenum, jejunum and ileum continue digestion and absorb most nutrients into the circulation.'],['small-intestine','duodenum','jejunum','ileum'],'abdomen',1.35)},
   {id:'portal',...L(['6 · สารอาหารเดินทางไปตับ','6 · Absorbed nutrients travel to the liver'],['เลือดจากทางเดินอาหารที่มีสารอาหารถูกส่งผ่าน hepatic portal vein ไปยังตับเพื่อประมวลผลก่อนเข้าสู่ระบบไหลเวียนทั่วไป','Nutrient-rich blood from the digestive tract travels through the hepatic portal vein to the liver for processing before joining general circulation.'],['small-intestine','liver','portal-vein'],'abdomen',1.38)},
   {id:'large-intestine',...L(['7 · ลำไส้ใหญ่ดูดซึมน้ำ','7 · The large intestine reclaims water'],['ลำไส้ใหญ่ดูดซึมน้ำและเกลือแร่บางส่วน พร้อมรวบรวมกากอาหารเข้าสู่ไส้ตรง','The large intestine absorbs water and some electrolytes while compacting waste and moving it toward the rectum.'],['large-intestine','rectum'],'abdomen',1.35)}
  ]
 },
 nervous:{
  icon:'✦',system:'nervous',title:['ระบบประสาท','Nervous system'],start:['เปิดบทเรียนระบบประสาท','Start nervous-system lesson'],simulation:{heart:false,blood:false,lungs:false,gut:false,air:false,urine:false,signal:true},
  steps:[
   {id:'overview',...L(['1 · ศูนย์ควบคุมของร่างกาย','1 · The body’s control network'],['ระบบประสาทรับข้อมูล ประมวลผล และส่งคำสั่ง โดยมีสมอง ก้านสมอง และไขสันหลังเป็นแกนกลางสำคัญ','The nervous system receives information, processes it and sends commands, with the brain, brainstem and spinal cord forming the central core.'],['brain','cerebellum','brainstem','spinal-cord'],'body',1.16)},
   {id:'sensory',...L(['2 · รับข้อมูลจากประสาทสัมผัส','2 · Sensory information enters'],['ตาและหูเป็นตัวอย่างอวัยวะรับความรู้สึกที่เปลี่ยนสิ่งเร้าเป็นสัญญาณส่งเข้าสู่ระบบประสาท','The eyes and ears are examples of sensory organs that convert stimuli into signals for the nervous system.'],['eye--1','eye-1','ear--1','ear-1','brain'],'head',1.25)},
   {id:'cerebrum',...L(['3 · สมองใหญ่ประมวลผล','3 · The cerebrum processes information'],['สมองใหญ่เกี่ยวข้องกับความรู้สึก ความคิด ความจำ ภาษา และการควบคุมการเคลื่อนไหวโดยสมัครใจ','The cerebrum supports sensation, thought, memory, language and voluntary motor control.'],['brain'],'head',1.7)},
   {id:'cerebellum',...L(['4 · สมองน้อยช่วยประสานการเคลื่อนไหว','4 · The cerebellum coordinates movement'],['สมองน้อยช่วยปรับความแม่นยำของการเคลื่อนไหว การทรงตัว และการประสานงานของกล้ามเนื้อ','The cerebellum refines movement accuracy, balance and muscular coordination.'],['cerebellum','brainstem'],'head',1.7)},
   {id:'brainstem',...L(['5 · ก้านสมองควบคุมงานอัตโนมัติสำคัญ','5 · Brainstem and vital automatic functions'],['ก้านสมองเชื่อมสมองกับไขสันหลัง และเกี่ยวข้องกับการควบคุมหน้าที่อัตโนมัติที่จำเป็นต่อชีวิต','The brainstem links the brain with the spinal cord and participates in vital automatic functions.'],['brainstem','spinal-cord'],'head',1.5)},
   {id:'spinal',...L(['6 · ไขสันหลังเป็นทางผ่านสัญญาณ','6 · The spinal cord carries signals'],['ไขสันหลังเป็นเส้นทางหลักระหว่างสมองกับร่างกาย และยังมีบทบาทในรีเฟล็กซ์บางชนิด','The spinal cord is a major communication route between brain and body and also participates in some reflexes.'],['brainstem','spinal-cord'],'body',1.25)}
  ]
 },
 urinary:{
  icon:'◆',system:'urinary',title:['ระบบทางเดินปัสสาวะ','Urinary system'],start:['เปิดบทเรียนระบบทางเดินปัสสาวะ','Start urinary-system lesson'],simulation:{heart:false,blood:false,lungs:false,gut:false,air:false,urine:true,signal:false},
  steps:[
   {id:'overview',...L(['1 · ไตและทางเดินปัสสาวะ','1 · Kidneys and urinary tract'],['ระบบทางเดินปัสสาวะประกอบด้วยไต ท่อไต กระเพาะปัสสาวะ และท่อปัสสาวะ ทำงานร่วมกันเพื่อสร้างและขับปัสสาวะ','The urinary tract includes the kidneys, ureters, bladder and urethra, working together to produce, store and eliminate urine.'],['kidney--1','kidney-1','ureter--1','ureter-1','bladder','urethra'],'abdomen',1.15)},
   {id:'blood-supply',...L(['2 · เลือดเข้าสู่ไต','2 · Blood reaches the kidneys'],['ไตได้รับเลือดผ่าน renal arteries และส่งเลือดกลับผ่าน renal veins เพื่อให้กระบวนการกรองและปรับสมดุลเกิดขึ้น','The kidneys receive blood through the renal arteries and return it through renal veins, supporting filtration and homeostatic regulation.'],['renal-artery--1','renal-artery-1','kidney--1','kidney-1','renal-vein--1','renal-vein-1'],'abdomen',1.35)},
   {id:'kidney',...L(['3 · ไตกรองและปรับสมดุล','3 · Kidneys filter and regulate'],['ไตกรองพลาสมาและปรับการเก็บหรือขับน้ำ เกลือแร่ และสารต่าง ๆ เพื่อสร้างปัสสาวะ','The kidneys filter plasma and adjust the retention or excretion of water, electrolytes and other substances to form urine.'],['kidney--1','kidney-1'],'abdomen',1.62)},
   {id:'ureters',...L(['4 · ปัสสาวะไหลลงท่อไต','4 · Urine travels through the ureters'],['ปัสสาวะจากไตถูกลำเลียงลงสู่กระเพาะปัสสาวะผ่านท่อไตทั้งสองข้าง โดยการบีบตัวของผนังท่อช่วยดันของเหลว','Urine moves from each kidney to the bladder through the ureters, aided by rhythmic contractions of their walls.'],['kidney--1','kidney-1','ureter--1','ureter-1','bladder'],'abdomen',1.3)},
   {id:'bladder',...L(['5 · กระเพาะปัสสาวะเก็บปัสสาวะ','5 · The bladder stores urine'],['กระเพาะปัสสาวะเป็นถุงกล้ามเนื้อที่ขยายตัวเพื่อเก็บปัสสาวะชั่วคราวก่อนการขับถ่าย','The urinary bladder is a muscular reservoir that expands to temporarily store urine before elimination.'],['bladder','ureter--1','ureter-1'],'pelvis',1.65)},
   {id:'urethra',...L(['6 · ขับออกทางท่อปัสสาวะ','6 · Elimination through the urethra'],['เมื่อเหมาะสม กล้ามเนื้อกระเพาะปัสสาวะบีบตัวและปัสสาวะไหลออกจากร่างกายผ่านท่อปัสสาวะ','At the appropriate time, bladder contraction drives urine out of the body through the urethra.'],['bladder','urethra'],'pelvis',1.6)}
  ]
 }
};

lessons.skeletal={icon:'✧',system:'skeletal',title:['ระบบโครงกระดูก','Skeletal system'],start:['เปิดบทเรียนระบบโครงกระดูก','Start skeletal-system lesson'],simulation:{heart:false,blood:false,lungs:false,gut:false,air:false,urine:false,signal:false},steps:[
 {id:'axial',...L(['1 · โครงกระดูกแกนกลาง','1 · Axial skeleton'],['กะโหลก กระดูกสันหลัง ซี่โครง และกระดูกอกสร้างแกนกลาง ช่วยพยุงและป้องกันอวัยวะสำคัญ','The skull, vertebral column, ribs and sternum form the axial skeleton, supporting the body and protecting vital organs.'],['skull','mandible','vertebra-C1','vertebra-T1','vertebra-L1','sternum','rib-1-1','rib--1-1'],'body',1.18)},
 {id:'skull',...L(['2 · กะโหลกป้องกันสมอง','2 · Skull protects the brain'],['กะโหลกสร้างโครงแข็งรอบสมอง ขณะที่ขากรรไกรล่างเป็นกระดูกสำคัญที่เคลื่อนไหวในการบดเคี้ยว','The cranium forms a rigid case around the brain, while the mandible is a major movable bone for chewing.'],['skull','mandible','brain'],'head',1.45)},
 {id:'spine',...L(['3 · กระดูกสันหลังรับน้ำหนักและป้องกันไขสันหลัง','3 · Vertebral column supports and protects'],['กระดูกคอ อก และเอวเรียงต่อกันเป็นแนวที่รับน้ำหนัก ช่วยเคลื่อนไหวลำตัว และล้อมรอบไขสันหลัง','Cervical, thoracic and lumbar vertebrae form a load-bearing, mobile column surrounding the spinal cord.'],['vertebra-C1','vertebra-C7','vertebra-T1','vertebra-T12','vertebra-L1','vertebra-L5','sacrum','coccyx','spinal-cord'],'body',1.2)},
 {id:'upper-limb',...L(['4 · โครงกระดูกแขนและมือ','4 · Upper-limb skeleton'],['ไหปลาร้าและสะบักเชื่อมแขนกับลำตัว ส่วน humerus, radius และ ulna เป็นแกนของแขนและปลายแขน','The clavicle and scapula attach the upper limb to the trunk; humerus, radius and ulna form the main arm and forearm framework.'],['clavicle-1','clavicle--1','scapula-1','scapula--1','humerus-1','humerus--1','radius-1','radius--1','ulna-1','ulna--1'],'chest',1.12)},
 {id:'pelvis-lower',...L(['5 · เชิงกราน ขา และเท้า','5 · Pelvis and lower limbs'],['กระดูกสะโพกรับและถ่ายน้ำหนักลงสู่ femur แล้วผ่าน tibia และกระดูกเท้าสู่พื้น','The hip bones transfer body weight to the femur, then through the tibia and foot bones to the ground.'],['hip-1','hip--1','femur-1','femur--1','patella-1','patella--1','tibia-1','tibia--1','fibula-1','fibula--1'],'legs',1.15)},
 {id:'joints',...L(['6 · กระดูกทำงานร่วมกับข้อต่อและกล้ามเนื้อ','6 · Bones work with joints and muscles'],['การเคลื่อนไหวเกิดจากกล้ามเนื้อสร้างแรงผ่านข้อต่อ โดยกระดูกทำหน้าที่เป็นคานและจุดยึดเกาะ','Movement arises when muscles generate force across joints, with bones acting as levers and attachment sites.'],['humerus-1','radius-1','ulna-1','femur-1','tibia-1','deltoid-1','quadriceps-1'],'body',1.12)}]};

lessons.muscular={icon:'◆',system:'muscular',title:['ระบบกล้ามเนื้อ','Muscular system'],start:['เปิดบทเรียนระบบกล้ามเนื้อ','Start muscular-system lesson'],simulation:{heart:false,blood:false,lungs:false,gut:false,air:false,urine:false,signal:false},steps:[
 {id:'overview',...L(['1 · กล้ามเนื้อสร้างการเคลื่อนไหว','1 · Muscles create movement'],['กล้ามเนื้อโครงร่างหดตัวเพื่อดึงกระดูกผ่านข้อต่อ ทำให้เกิดการเคลื่อนไหวและช่วยคงท่าทาง','Skeletal muscles contract to pull bones across joints, producing movement and helping maintain posture.'],['deltoid-1','pectoralis-1','biceps-1','triceps-1','rectus-1','quadriceps-1','hamstrings-1'],'body',1.12)},
 {id:'shoulder-arm',...L(['2 · ไหล่และแขน','2 · Shoulder and arm muscles'],['deltoid ช่วยยกแขน ขณะที่ biceps และ triceps ทำงานเป็นคู่ตรงข้ามในการงอและเหยียดข้อศอก','The deltoid helps raise the arm, while biceps and triceps act as an opposing pair for elbow flexion and extension.'],['deltoid-1','deltoid--1','biceps-1','biceps--1','triceps-1','triceps--1'],'chest',1.2)},
 {id:'trunk',...L(['3 · กล้ามเนื้อลำตัว','3 · Trunk muscles'],['pectoralis, rectus abdominis, oblique, trapezius และ latissimus ช่วยเคลื่อนไหวลำตัว แขน และรักษาเสถียรภาพ','Pectoralis, rectus abdominis, obliques, trapezius and latissimus contribute to trunk and arm movement and stability.'],['pectoralis-1','pectoralis--1','rectus-1','rectus--1','oblique-1','oblique--1','trapezius-1','trapezius--1','latissimus-1','latissimus--1'],'chest',1.12)},
 {id:'hip-thigh',...L(['4 · สะโพกและต้นขา','4 · Hip and thigh muscles'],['gluteus ช่วยเหยียดข้อสะโพก ส่วน quadriceps และ hamstrings เป็นกลุ่มสำคัญที่ควบคุมเข่าและสะโพก','Gluteal muscles help extend the hip; quadriceps and hamstrings are major groups controlling knee and hip motion.'],['gluteus-1','gluteus--1','quadriceps-1','quadriceps--1','hamstrings-1','hamstrings--1'],'legs',1.28)},
 {id:'lower-leg',...L(['5 · กล้ามเนื้อน่องและหน้าแข้ง','5 · Lower-leg muscles'],['gastrocnemius ช่วยกดปลายเท้าลง ส่วน tibialis anterior ช่วยยกปลายเท้าขึ้น จึงมีบทบาทสำคัญในการเดิน','Gastrocnemius plantar-flexes the foot, while tibialis anterior dorsiflexes it; both are important during walking.'],['gastrocnemius-1','gastrocnemius--1','tibialis-1','tibialis--1'],'legs',1.35)},
 {id:'antagonists',...L(['6 · คู่กล้ามเนื้อทำงานสลับกัน','6 · Antagonistic muscle pairs'],['หลายข้อต่อควบคุมด้วยกล้ามเนื้อคู่ตรงข้าม เมื่อกลุ่มหนึ่งหดตัว อีกกลุ่มจะคลายหรือควบคุมแรงอย่างประสานกัน','Many joints are controlled by opposing muscle groups: as one contracts, the other relaxes or modulates force in coordination.'],['biceps-1','triceps-1','quadriceps-1','hamstrings-1'],'body',1.22)}]};

lessons.endocrine={icon:'●',system:'endocrine',title:['ระบบต่อมไร้ท่อ','Endocrine system'],start:['เปิดบทเรียนระบบต่อมไร้ท่อ','Start endocrine-system lesson'],simulation:{heart:false,blood:false,lungs:false,gut:false,air:false,urine:false,signal:false},steps:[
 {id:'overview',...L(['1 · ฮอร์โมนเป็นสารส่งสัญญาณ','1 · Hormones are chemical messengers'],['ต่อมไร้ท่อหลั่งฮอร์โมนเข้าสู่เลือดเพื่อปรับการทำงานของอวัยวะเป้าหมาย เช่น การเจริญเติบโต การเผาผลาญ และการตอบสนองต่อความเครียด','Endocrine glands release hormones into blood to regulate target organs, including growth, metabolism and stress responses.'],['pituitary','pineal','thyroid--1','thyroid-1','adrenal--1','adrenal-1','pancreas'],'body',1.15)},
 {id:'pituitary',...L(['2 · ต่อมใต้สมอง','2 · Pituitary gland'],['ต่อมใต้สมองอยู่บริเวณฐานสมองและหลั่งฮอร์โมนหลายชนิดที่มีผลต่อการเจริญเติบโตและต่อมอื่น ๆ','The pituitary lies near the base of the brain and releases multiple hormones that influence growth and other endocrine glands.'],['brain','pituitary'],'head',1.65)},
 {id:'pineal',...L(['3 · ต่อมไพเนียลและวงจรหลับ–ตื่น','3 · Pineal gland and sleep–wake timing'],['ต่อมไพเนียลสร้างเมลาโทนิน ซึ่งมีบทบาทในการกำหนดจังหวะหลับ–ตื่นของร่างกาย','The pineal gland produces melatonin, which contributes to regulation of the sleep–wake cycle.'],['brain','pineal'],'head',1.65)},
 {id:'thyroid',...L(['4 · ไทรอยด์ควบคุมการเผาผลาญ','4 · Thyroid and metabolic regulation'],['ต่อมไทรอยด์บริเวณคอสร้างฮอร์โมนที่มีผลต่ออัตราการใช้พลังงานและการทำงานของหลายเนื้อเยื่อ','The thyroid in the neck produces hormones that influence energy use and activity across many tissues.'],['thyroid--1','thyroid-1'],'head',1.55)},
 {id:'adrenal',...L(['5 · ต่อมหมวกไตตอบสนองต่อความเครียด','5 · Adrenal glands and stress responses'],['ต่อมหมวกไตอยู่เหนือไตและสร้างฮอร์โมนหลายชนิดที่เกี่ยวข้องกับความดันเลือด สมดุลเกลือแร่ และการตอบสนองต่อความเครียด','The adrenal glands sit above the kidneys and produce hormones involved in blood pressure, electrolyte balance and stress responses.'],['adrenal--1','adrenal-1','kidney--1','kidney-1'],'abdomen',1.42)},
 {id:'pancreas',...L(['6 · ตับอ่อนช่วยควบคุมกลูโคส','6 · Pancreas and glucose control'],['ตับอ่อนมีเซลล์ต่อมไร้ท่อที่หลั่งอินซูลินและกลูคากอนเพื่อช่วยควบคุมระดับกลูโคสในเลือด','The pancreas contains endocrine cells that release insulin and glucagon, helping regulate blood glucose.'],['pancreas'],'abdomen',1.65)}]};

lessons.lymphatic={icon:'✤',system:'lymphatic',title:['ระบบน้ำเหลืองและภูมิคุ้มกัน','Lymphatic & immune system'],start:['เปิดบทเรียนระบบน้ำเหลือง','Start lymphatic-system lesson'],simulation:{heart:false,blood:false,lungs:false,gut:false,air:false,urine:false,signal:false},steps:[
 {id:'overview',...L(['1 · เครือข่ายป้องกันและคืนของเหลว','1 · Defense and fluid return network'],['ระบบน้ำเหลืองช่วยคืนของเหลวจากเนื้อเยื่อสู่ระบบไหลเวียน และเป็นส่วนสำคัญของภูมิคุ้มกัน','The lymphatic system returns tissue fluid to circulation and is an important part of immune defense.'],['thymus','spleen','nodes-cervical-1','nodes-cervical1','nodes-axillary-1','nodes-axillary1','nodes-inguinal-1','nodes-inguinal1'],'body',1.15)},
 {id:'nodes',...L(['2 · ต่อมน้ำเหลืองเป็นจุดตรวจ','2 · Lymph nodes act as checkpoints'],['ต่อมน้ำเหลืองกรองน้ำเหลืองและเป็นบริเวณที่เซลล์ภูมิคุ้มกันพบและตอบสนองต่อสิ่งแปลกปลอม','Lymph nodes filter lymph and provide sites where immune cells encounter and respond to foreign material.'],['nodes-cervical-1','nodes-cervical1','nodes-axillary-1','nodes-axillary1','nodes-inguinal-1','nodes-inguinal1'],'body',1.18)},
 {id:'cervical',...L(['3 · ต่อมน้ำเหลืองบริเวณคอ','3 · Cervical lymph nodes'],['กลุ่มต่อมน้ำเหลืองบริเวณคอช่วยรับน้ำเหลืองจากศีรษะและคอบางส่วน','Cervical lymph-node groups receive lymph from regions of the head and neck.'],['nodes-cervical-1','nodes-cervical1'],'head',1.5)},
 {id:'thymus',...L(['4 · ไทมัสและการพัฒนาทีเซลล์','4 · Thymus and T-cell development'],['ไทมัสเป็นอวัยวะสำคัญต่อการพัฒนาทีลิมโฟไซต์ โดยเด่นมากในวัยเด็กและมีขนาดลดลงเมื่ออายุมากขึ้น','The thymus is important for T-lymphocyte development, especially early in life, and becomes smaller with age.'],['thymus'],'chest',1.65)},
 {id:'spleen',...L(['5 · ม้ามกรองเลือด','5 · Spleen filters blood'],['ม้ามกรองเลือด ช่วยกำจัดเซลล์เม็ดเลือดแดงที่เสื่อม และสนับสนุนการตอบสนองทางภูมิคุ้มกัน','The spleen filters blood, helps remove aged red blood cells and supports immune responses.'],['spleen'],'abdomen',1.65)},
 {id:'regional',...L(['6 · ต่อมน้ำเหลืองตามภูมิภาค','6 · Regional lymph nodes'],['กลุ่มรักแร้และขาหนีบเป็นตัวอย่างของต่อมน้ำเหลืองที่รับน้ำเหลืองจากแขน ขา และบริเวณใกล้เคียง','Axillary and inguinal groups illustrate regional nodes receiving lymph from the limbs and nearby tissues.'],['nodes-axillary-1','nodes-axillary1','nodes-inguinal-1','nodes-inguinal1'],'body',1.2)}]};

lessons.reproductive={icon:'◉',system:'reproductive',title:['ระบบสืบพันธุ์','Reproductive system'],start:['เปิดบทเรียนระบบสืบพันธุ์','Start reproductive-system lesson'],simulation:{heart:false,blood:false,lungs:false,gut:false,air:false,urine:false,signal:false},steps:[
 {id:'female-overview',sex:'female',...L(['1 · โครงสร้างสืบพันธุ์เพศหญิง','1 · Female reproductive anatomy'],['รังไข่ ท่อนำไข่ มดลูก ปากมดลูก ช่องคลอด และอวัยวะเพศภายนอกทำงานร่วมกันในการสร้างเซลล์สืบพันธุ์ การปฏิสนธิ การตั้งครรภ์ และการคลอด','The ovaries, uterine tubes, uterus, cervix, vagina and external genital structures work together in gamete production, fertilization, pregnancy and birth.'],['uterus','cervix','vagina','ovary--1','ovary-1','tube--1','tube-1','vulva','clitoris'],'pelvis',1.3)},
 {id:'ovaries',sex:'female',...L(['2 · รังไข่','2 · Ovaries'],['รังไข่สร้างเซลล์ไข่และฮอร์โมนเพศหลายชนิด มีตำแหน่งอยู่ด้านข้างของมดลูก','The ovaries produce oocytes and several sex hormones and lie lateral to the uterus.'],['ovary--1','ovary-1','uterus'],'pelvis',1.65)},
 {id:'uterine-tubes',sex:'female',...L(['3 · ท่อนำไข่','3 · Uterine tubes'],['ท่อนำไข่ลำเลียงเซลล์ไข่จากบริเวณรังไข่เข้าสู่มดลูก และเป็นตำแหน่งที่การปฏิสนธิมักเกิดขึ้น','The uterine tubes carry the oocyte toward the uterus and are a common site of fertilization.'],['tube--1','tube-1','ovary--1','ovary-1','uterus'],'pelvis',1.5)},
 {id:'uterus-cervix',sex:'female',...L(['4 · มดลูก ปากมดลูก และช่องคลอด','4 · Uterus, cervix and vagina'],['มดลูกรองรับการฝังตัวและการตั้งครรภ์ ปากมดลูกเป็นส่วนล่างของมดลูกที่เปิดเข้าสู่ช่องคลอด ซึ่งเป็นทางเชื่อมสู่ภายนอก','The uterus supports implantation and pregnancy. The cervix is the lower uterine opening into the vagina, which connects to the exterior.'],['uterus','cervix','vagina'],'pelvis',1.55)},
 {id:'female-external',sex:'female',...L(['5 · อวัยวะเพศภายนอกหญิง','5 · Female external genitalia'],['อวัยวะเพศภายนอกหญิงหรือ vulva ประกอบด้วยแคมใหญ่ แคมเล็ก และคลิตอริส ช่วยปกป้องช่องเปิดและมีบทบาทด้านความรู้สึก','The vulva includes the labia majora, labia minora and clitoris, helping protect the openings and contributing to sensation.'],['vulva','labium-majus--1','labium-majus-1','labium-minus--1','labium-minus-1','clitoris'],'pelvis',1.55)},
 {id:'male-overview',sex:'male',...L(['6 · โครงสร้างสืบพันธุ์เพศชาย','6 · Male reproductive anatomy'],['ระบบสืบพันธุ์ชายประกอบด้วยอัณฑะ หลอดเก็บอสุจิ ท่อนำอสุจิ ถุงน้ำเชื้อ ต่อมลูกหมาก ต่อมคาวเปอร์ ท่อหลั่ง ถุงอัณฑะ และองคชาต','The male reproductive system includes the testes, epididymides, vasa deferentia, seminal vesicles, prostate, bulbourethral glands, ejaculatory ducts, scrotum and penis.'],['testis--1','testis-1','epididymis--1','epididymis-1','vas-deferens--1','vas-deferens-1','seminal-vesicle--1','seminal-vesicle-1','prostate','scrotum','penis'],'pelvis',1.25)},
 {id:'sperm-path',sex:'male',...L(['7 · เส้นทางของอสุจิ','7 · Sperm pathway'],['อสุจิสร้างในอัณฑะ เจริญสมบูรณ์ในหลอดเก็บอสุจิ จากนั้นเดินทางผ่านท่อนำอสุจิและท่อหลั่งเข้าสู่ท่อปัสสาวะ','Sperm are produced in the testes, mature in the epididymis, then travel through the vas deferens and ejaculatory duct toward the urethra.'],['testis--1','testis-1','epididymis--1','epididymis-1','vas-deferens--1','vas-deferens-1','ejaculatory-duct--1','ejaculatory-duct-1','prostate'],'pelvis',1.35)},
 {id:'male-glands-external',sex:'male',...L(['8 · ต่อมประกอบและอวัยวะภายนอกชาย','8 · Accessory glands and male external anatomy'],['ถุงน้ำเชื้อ ต่อมลูกหมาก และต่อมคาวเปอร์สร้างของเหลวที่รวมเป็นส่วนหนึ่งของน้ำอสุจิ ส่วนถุงอัณฑะรองรับอัณฑะและองคชาตเป็นทางผ่านของท่อปัสสาวะสู่ภายนอก','The seminal vesicles, prostate and bulbourethral glands contribute fluids to semen. The scrotum supports the testes, and the penis carries the urethra to the exterior.'],['seminal-vesicle--1','seminal-vesicle-1','prostate','bulbourethral--1','bulbourethral-1','scrotum','penis','urethra'],'pelvis',1.35)}]};

lessons.sensory={icon:'◎',system:'sensory',title:['อวัยวะรับความรู้สึก','Sense organs'],start:['เปิดบทเรียนอวัยวะรับความรู้สึก','Start sense-organ lesson'],simulation:{heart:false,blood:false,lungs:false,gut:false,air:false,urine:false,signal:true},steps:[
 {id:'overview',...L(['1 · รับสิ่งเร้าจากสิ่งแวดล้อม','1 · Detecting environmental stimuli'],['อวัยวะรับความรู้สึกเปลี่ยนแสง เสียง สารเคมี และสิ่งเร้าอื่นเป็นสัญญาณที่ระบบประสาทนำไปประมวลผล','Sense organs convert light, sound, chemicals and other stimuli into signals for nervous-system processing.'],['eye--1','eye-1','ear--1','ear-1','tongue','nasal-cavity','brain'],'head',1.25)},
 {id:'eyes',...L(['2 · ตาและการมองเห็น','2 · Eyes and vision'],['ตารับแสงและจอตาเปลี่ยนพลังงานแสงเป็นสัญญาณประสาทที่สมองใช้สร้างการรับรู้ทางการมองเห็น','The eyes receive light and the retina converts it into neural signals used by the brain for visual perception.'],['eye--1','eye-1','brain'],'head',1.5)},
 {id:'ears',...L(['3 · หูและการได้ยิน','3 · Ears and hearing'],['ใบหูช่วยรวบรวมคลื่นเสียงเข้าสู่ช่องหู ก่อนที่ระบบภายในหูจะเปลี่ยนการสั่นสะเทือนเป็นสัญญาณประสาท','The auricle collects sound waves into the ear canal before internal structures convert vibrations into neural signals.'],['ear--1','ear-1','brain'],'head',1.5)},
 {id:'taste',...L(['4 · ลิ้นและการรับรส','4 · Tongue and taste'],['ตัวรับรสบนลิ้นตอบสนองต่อสารเคมีในอาหารและส่งข้อมูลไปยังระบบประสาท','Taste receptors on the tongue respond to chemicals in food and relay information to the nervous system.'],['tongue','brainstem','brain'],'head',1.5)},
 {id:'smell',...L(['5 · โพรงจมูกและการรับกลิ่น','5 · Nasal cavity and smell'],['บริเวณรับกลิ่นในโพรงจมูกตรวจจับโมเลกุลกลิ่นและส่งสัญญาณเข้าสู่สมอง','Olfactory regions in the nasal cavity detect odor molecules and relay signals toward the brain.'],['nasal-cavity','brain'],'head',1.5)},
 {id:'integration',...L(['6 · สมองรวมข้อมูลจากหลายประสาทสัมผัส','6 · Brain integrates sensory information'],['สมองรวมข้อมูลจากหลายช่องทางเพื่อสร้างการรับรู้และช่วยกำหนดการตอบสนองของร่างกาย','The brain combines information from multiple sensory channels to create perception and guide responses.'],['brain','cerebellum','brainstem','eye--1','eye-1','ear--1','ear-1'],'head',1.3)}]};

lessons.integumentary={icon:'◇',system:'integumentary',title:['ระบบผิวหนัง','Integumentary system'],start:['เปิดบทเรียนระบบผิวหนัง','Start integumentary-system lesson'],simulation:{heart:false,blood:false,lungs:false,gut:false,air:false,urine:false,signal:false},steps:[
 {id:'envelope',...L(['1 · ผิวหนังห่อหุ้มร่างกาย','1 · Skin forms the body envelope'],['ผิวหนังเป็นอวัยวะขนาดใหญ่ที่ห่อหุ้มผิวภายนอก แยกสภาพแวดล้อมภายในร่างกายออกจากภายนอก','Skin is a large organ covering the external body surface and separating the internal environment from the outside world.'],['skin'],'body',1.04)},
 {id:'barrier',...L(['2 · เกราะป้องกัน','2 · Protective barrier'],['ผิวหนังช่วยลดการสูญเสียน้ำและเป็นด่านกายภาพต่อการบาดเจ็บ สารระคายเคือง และจุลชีพบางชนิด','Skin reduces water loss and provides a physical barrier against injury, irritants and many microorganisms.'],['skin'],'body',1.04)},
 {id:'temperature',...L(['3 · การควบคุมอุณหภูมิ','3 · Temperature regulation'],['หลอดเลือดผิวหนังและต่อมเหงื่อมีบทบาทช่วยปรับการระบายความร้อนของร่างกาย แม้รายละเอียดระดับนี้ไม่ได้แยกในโมเดล','Skin blood vessels and sweat glands help regulate heat loss, although these microscopic details are not separately modeled here.'],['skin'],'body',1.04)},
 {id:'sensation',...L(['4 · การรับสัมผัส','4 · Cutaneous sensation'],['ตัวรับความรู้สึกในผิวหนังช่วยตรวจจับการสัมผัส แรงกด อุณหภูมิ และความเจ็บปวด แล้วส่งข้อมูลเข้าสู่ระบบประสาท','Sensory receptors in skin detect touch, pressure, temperature and pain and relay information to the nervous system.'],['skin','spinal-cord','brain'],'body',1.08)}]};

lessons.circulation.steps.push(
 {id:'coronary',...L(['8 · หลอดเลือดเลี้ยงหัวใจ','8 · Coronary circulation'],['กล้ามเนื้อหัวใจต้องได้รับเลือดของตนเองผ่าน coronary arteries และเลือดดำไหลกลับผ่าน cardiac veins สู่ coronary sinus','The myocardium receives its own blood through coronary arteries; venous blood returns through cardiac veins to the coronary sinus.'],['left-coronary-artery','right-coronary-artery','great-cardiac-vein','coronary-sinus','heart'],'chest',1.55)},
 {id:'conduction',...L(['9 · ระบบนำไฟฟ้าหัวใจ','9 · Cardiac conduction'],['SA node เริ่มจังหวะ จากนั้นสัญญาณผ่าน AV node, Bundle of His และ Purkinje network เพื่อประสานการบีบตัวของหัวใจ','The SA node initiates the rhythm, followed by the AV node, Bundle of His and Purkinje network to coordinate contraction.'],['sa-node','av-node','bundle-his','purkinje-network','myocardium'],'chest',1.65)},
 {id:'upper-limb-vessels',...L(['10 · เลือดสู่แขนและมือ','10 · Blood to the upper limbs'],['subclavian artery ต่อสู่หลอดเลือดแขน ก่อนแยกเป็น radial และ ulnar arteries ที่ปลายแขนและมือ','The subclavian artery continues toward the arm and ultimately gives rise to radial and ulnar arteries in the forearm and hand.'],['subclavian-artery--1','subclavian-artery-1','brachial-artery--1','brachial-artery-1','radial-artery--1','radial-artery-1','ulnar-artery--1','ulnar-artery-1'],'body',1.08)},
 {id:'lower-limb-vessels',...L(['11 · เลือดสู่เชิงกรานและขา','11 · Blood to the pelvis and legs'],['aorta แยกเป็น common iliac arteries แล้วต่อไปยัง femoral และ tibial arteries ส่วนเลือดดำกลับผ่าน iliac veins สู่ inferior vena cava','The aorta divides into common iliac arteries leading toward femoral and tibial arteries; venous blood returns through iliac veins to the inferior vena cava.'],['common-iliac-artery--1','common-iliac-artery-1','femoral-artery--1','femoral-artery-1','anterior-tibial-artery--1','anterior-tibial-artery-1','posterior-tibial-artery--1','posterior-tibial-artery-1','common-iliac-vein--1','common-iliac-vein-1','inferior-vena-cava'],'body',1.05)}
);

lessons.respiratory.steps.push(
 {id:'pharynx-epiglottis',...L(['7 · คอหอยและฝาปิดกล่องเสียง','7 · Pharynx and epiglottis'],['คอหอยเป็นทางผ่านร่วมของอากาศและอาหาร ขณะกลืน epiglottis ช่วยป้องกันอาหารเข้าสู่กล่องเสียง','The pharynx is shared by air and food; during swallowing, the epiglottis helps protect the laryngeal inlet.'],['nasal-cavity','pharynx','epiglottis','larynx'],'head',1.45)},
 {id:'bronchioles-alveoli',...L(['8 · จากหลอดลมฝอยถึงถุงลม','8 · From bronchioles to alveoli'],['หลอดลมฝอยนำอากาศเข้าสู่ alveolar sacs และ alveoli ซึ่งผนังบางอยู่ใกล้เส้นเลือดฝอยเพื่อแลกเปลี่ยนแก๊ส','Bronchioles conduct air to alveolar sacs and alveoli, whose thin walls lie close to capillaries for gas exchange.'],['bronchioles--1','bronchioles-1','alveolar-sac--1','alveolar-sac-1','alveolus--1-1','alveolus-1-1'],'chest',1.45)},
 {id:'pleura',...L(['9 · เยื่อหุ้มปอด','9 · Pleura'],['pleura ช่วยให้ปอดเคลื่อนตัวกับผนังทรวงอกโดยมีแรงเสียดทานต่ำ และช่วยคงกลไกความดันที่ทำให้ปอดขยายตามทรวงอก','The pleura permits low-friction movement and helps maintain the pressure relationship that couples the lungs to thoracic expansion.'],['pleura--1','pleura-1','lung-right','lung-left','diaphragm'],'chest',1.35)}
);

lessons.digestive.steps.push(
 {id:'oral-saliva',...L(['8 · ช่องปาก ฟัน และน้ำลาย','8 · Oral cavity, teeth and saliva'],['ฟันตัด ฉีก และบดอาหาร ลิ้นช่วยคลุกเคล้า ขณะที่ต่อมน้ำลายหลั่งน้ำลายเพื่อหล่อลื่นและเริ่มย่อยสารอาหารบางชนิด','Teeth cut, tear and grind food; the tongue manipulates it while salivary glands lubricate food and begin digestion of some nutrients.'],['oral-cavity','tongue','upper-incisors','upper-canines','upper-premolars','upper-molars','parotid-gland-1','submandibular-gland-1','sublingual-gland-1'],'head',1.35)},
 {id:'colon-segments',...L(['9 · ส่วนต่าง ๆ ของลำไส้ใหญ่','9 · Segments of the large intestine'],['cecum ต่อสู่ ascending, transverse, descending และ sigmoid colon ก่อนเข้าสู่ rectum โดยมีการดูดซึมน้ำและเคลื่อนกากอาหารต่อเนื่อง','The cecum continues into ascending, transverse, descending and sigmoid colon before the rectum, reclaiming water and moving fecal material.'],['cecum','ascending-colon','transverse-colon','descending-colon','sigmoid-colon','rectum'],'abdomen',1.28)},
 {id:'bile-pancreatic-ducts',...L(['10 · น้ำดีและน้ำย่อยเข้าสู่ duodenum','10 · Bile and pancreatic secretions enter the duodenum'],['common bile duct และ pancreatic duct นำสารคัดหลั่งจากตับ/ถุงน้ำดีและตับอ่อนเข้าสู่ลำไส้เล็กส่วนต้นเพื่อช่วยย่อย','The common bile duct and pancreatic duct deliver biliary and pancreatic secretions into the duodenum to support digestion.'],['liver','gallbladder','common-bile-duct','pancreas','pancreatic-duct','duodenum'],'abdomen',1.42)},
 {id:'defecation',...L(['11 · ปลายทางของกากอาหาร','11 · Final passage of fecal material'],['กากอาหารเข้าสู่ rectum แล้วผ่าน anal canal และ anus ในกระบวนการขับถ่าย','Fecal material enters the rectum and then passes through the anal canal and anus during defecation.'],['sigmoid-colon','rectum','anal-canal','anus'],'pelvis',1.5)}
);

lessons.urinary.steps.push(
 {id:'kidney-layers',...L(['7 · เปลือกไตและเนื้อไตชั้นใน','7 · Renal cortex and medulla'],['renal cortex มี renal corpuscles จำนวนมาก ส่วน medulla ประกอบด้วย pyramids และท่อที่ช่วยสร้างความชันเพื่อทำให้ปัสสาวะเข้มข้น','The renal cortex contains many renal corpuscles, while the medulla contains pyramids and tubules that help create concentration gradients.'],['renal-cortex--1','renal-medulla--1','renal-pyramid--1-1','renal-cortex-1','renal-medulla-1','renal-pyramid-1-1'],'abdomen',1.52)},
 {id:'filtration',...L(['8 · การกรองที่ glomerulus','8 · Filtration at the glomerulus'],['เลือดผ่าน glomerulus น้ำและสารขนาดเล็กถูกกรองเข้าสู่ Bowman capsule เป็นจุดเริ่มต้นของน้ำกรองใน nephron','Blood passes through the glomerulus, where water and small solutes enter Bowman capsule to begin nephron filtrate.'],['glomerulus','bowman-capsule','nephron','renal-cortex-1'],'abdomen',1.65)},
 {id:'nephron-tubules',...L(['9 · การดูดกลับและปรับสมดุลในท่อหน่วยไต','9 · Tubular reabsorption and regulation'],['proximal tubule ดูดกลับสารจำนวนมาก Loop of Henle สร้างความชัน ส่วน distal tubule ปรับไอออนและกรด–ด่างก่อนเข้าสู่ collecting duct','The proximal tubule performs bulk reabsorption, the Loop of Henle builds concentration gradients and the distal tubule fine-tunes ions and acid-base balance before the collecting duct.'],['proximal-tubule','loop-henle','distal-tubule','collecting-duct','nephron'],'abdomen',1.65)},
 {id:'pelvis-calyces',...L(['10 · จาก pyramids สู่กรวยไต','10 · From pyramids to renal pelvis'],['ปัสสาวะไหลจาก papillae ของ pyramids เข้าสู่ calyces รวมใน renal pelvis แล้วลง ureter','Urine flows from renal papillae into calyces, collects in the renal pelvis and then enters the ureter.'],['renal-pyramid-1-1','renal-pyramid-1-2','renal-pyramid-1-3','renal-calyces-1','renal-pelvis-1','ureter-1'],'abdomen',1.5)}
);

lessons.endocrine.steps.push(
 {id:'parathyroid',...L(['7 · พาราไทรอยด์และสมดุลแคลเซียม','7 · Parathyroids and calcium balance'],['ต่อมพาราไทรอยด์ขนาดเล็กด้านหลังไทรอยด์หลั่ง PTH เพื่อช่วยควบคุมแคลเซียมในเลือดและสมดุลแร่ธาตุของกระดูก','Small parathyroid glands behind the thyroid release PTH to regulate blood calcium and bone mineral balance.'],['parathyroid--1-1','parathyroid--1-2','parathyroid-1-1','parathyroid-1-2','thyroid--1','thyroid-1','thyroid-isthmus'],'head',1.55)},
 {id:'adrenal-layers',...L(['8 · เปลือกและแกนต่อมหมวกไต','8 · Adrenal cortex and medulla'],['adrenal cortex สร้างฮอร์โมนสเตียรอยด์ ส่วน adrenal medulla หลั่ง catecholamines ในการตอบสนองต่อความเครียด','The adrenal cortex produces steroid hormones, while the adrenal medulla releases catecholamines during stress responses.'],['adrenal-cortex--1','adrenal-medulla--1','adrenal-cortex-1','adrenal-medulla-1'],'abdomen',1.48)},
 {id:'islets',...L(['9 · ไอส์เลตของตับอ่อน','9 · Pancreatic islets'],['กลุ่มเซลล์ต่อมไร้ท่อในตับอ่อนหลั่ง insulin และ glucagon เพื่อช่วยรักษาระดับกลูโคสในเลือด','Endocrine islets in the pancreas release insulin and glucagon to help maintain blood glucose.'],['pancreas','pancreatic-islet-1','pancreatic-islet-2','pancreatic-islet-3','pancreatic-islet-4','pancreatic-islet-5'],'abdomen',1.55)}
);

lessons.lymphatic.steps.push(
 {id:'vessels-ducts',...L(['7 · เครือข่ายหลอดและท่อน้ำเหลือง','7 · Lymphatic vessels and ducts'],['หลอดน้ำเหลืองจากแขนและขารวมเข้าสู่ทางเดินส่วนกลาง โดย thoracic duct รับน้ำเหลืองจากร่างกายส่วนใหญ่ ส่วน right lymphatic duct รับจากส่วนบนขวา','Lymphatic vessels from the limbs converge centrally; the thoracic duct drains most of the body while the right lymphatic duct drains the right upper quadrant.'],['upper-limb-lymphatics--1','upper-limb-lymphatics-1','lower-limb-lymphatics--1','lower-limb-lymphatics-1','thoracic-duct','right-lymphatic-duct'],'body',1.05)},
 {id:'cisterna',...L(['8 · ซิสเทอร์นาชิลี','8 · Cisterna chyli'],['cisterna chyli เป็นบริเวณขยายที่รับน้ำเหลืองจากช่องท้องและขาส่วนล่างก่อนเข้าสู่ thoracic duct','The cisterna chyli receives lymph from the abdomen and lower limbs before it enters the thoracic duct.'],['cisterna-chyli','thoracic-duct','mesenteric-node-1','mesenteric-node-2','mesenteric-node-3','mesenteric-node-4','mesenteric-node-5'],'abdomen',1.45)},
 {id:'immune-organs',...L(['9 · ทอนซิลและไขกระดูก','9 · Tonsils and bone marrow'],['tonsils ช่วยเฝ้าระวังสิ่งแปลกปลอมบริเวณคอหอย ขณะที่ไขกระดูกแดงสร้างเซลล์เม็ดเลือดและเซลล์ภูมิคุ้มกันระยะต้น','Tonsils sample material in the pharynx, while red bone marrow produces blood cells and immune-cell precursors.'],['palatine-tonsil--1','palatine-tonsil-1','red-bone-marrow','thymus','spleen'],'body',1.2)},
 {id:'intestinal-lymph',...L(['10 · การดูดซึมไขมันเข้าสู่น้ำเหลือง','10 · Dietary fat enters lymph'],['lacteals ในวิลไลของลำไส้เล็กรับไขมันจากอาหารเข้าสู่ระบบน้ำเหลือง ก่อนส่งกลับสู่กระแสเลือด','Lacteals in intestinal villi absorb dietary lipids into lymph before they return to the bloodstream.'],['small-intestine','intestinal-lacteals','mesenteric-node-2','mesenteric-node-3','mesenteric-node-4','cisterna-chyli','thoracic-duct'],'abdomen',1.35)}
);

lessons.integumentary.steps.push(
 {id:'layers',...L(['5 · ชั้นของผิวหนัง','5 · Skin layers'],['epidermis เป็นเกราะชั้นนอก dermis มีหลอดเลือด เส้นประสาท และต่อม ส่วน hypodermis ช่วยรองรับและเป็นฉนวน','The epidermis forms the outer barrier, the dermis contains vessels, nerves and glands, and the hypodermis provides cushioning and insulation.'],['epidermis','dermis','hypodermis'],'chest',1.65)},
 {id:'hair-glands',...L(['6 · ขนและต่อมของผิวหนัง','6 · Hair and skin glands'],['hair follicle สร้างเส้นขน ต่อมไขมันหลั่ง sebum และต่อมเหงื่อช่วยระบายความร้อน','Hair follicles produce hair, sebaceous glands release sebum and sweat glands support thermoregulation.'],['hair-shaft','hair-follicle','sebaceous-gland','sweat-gland','arrector-pili'],'chest',1.6)},
 {id:'skin-sensation',...L(['7 · ตัวรับความรู้สึกในผิวหนัง','7 · Cutaneous sensation'],['ตัวรับในผิวหนังเชื่อมกับระบบประสาทเพื่อตรวจจับการสัมผัส แรงกด การสั่น อุณหภูมิ และความเจ็บปวด','Skin receptors connect with the nervous system to detect touch, pressure, vibration, temperature and pain.'],['cutaneous-receptor','skin','spinal-cord'],'chest',1.45)},
 {id:'skin-circulation',...L(['8 · หลอดเลือดผิวหนังและการระบายความร้อน','8 · Skin blood flow and heat exchange'],['หลอดเลือดใน dermis ปรับการไหลเวียนใกล้ผิวเพื่อช่วยควบคุมการถ่ายเทความร้อน ขณะที่เหงื่อช่วยระบายความร้อนด้วยการระเหย','Dermal vessels regulate surface blood flow for heat exchange while sweat supports evaporative cooling.'],['cutaneous-vessel','dermis','sweat-gland'],'chest',1.55)}
);

lessons.nervous.steps.push(
 {id:'brain-regions',...L(['7 · แบ่งหน้าที่ภายในสมอง','7 · Functional regions inside the brain'],['กลีบหน้าผาก ข้างขม่อม ขมับ และท้ายทอยทำหน้าที่เด่นต่างกัน ขณะที่ thalamus และ hypothalamus เชื่อมการรับรู้ การควบคุมอัตโนมัติ และฮอร์โมน','The frontal, parietal, temporal and occipital lobes have distinct roles, while the thalamus and hypothalamus link perception, autonomic control and endocrine regulation.'],['frontal-lobe-1','parietal-lobe-1','temporal-lobe-1','occipital-lobe-1','thalamus','hypothalamus','corpus-callosum'],'head',1.42)},
 {id:'cranial-autonomic',...L(['8 · เส้นประสาทสมองและระบบอัตโนมัติ','8 · Cranial and autonomic pathways'],['trigeminal รับความรู้สึกใบหน้า ส่วน vagus และ sympathetic trunks เป็นเส้นทางสำคัญของการควบคุมอวัยวะอัตโนมัติ','The trigeminal nerve carries facial sensation, while the vagus nerves and sympathetic trunks are major autonomic pathways.'],['trigeminal-nerve--1','trigeminal-nerve-1','vagus-nerve--1','vagus-nerve-1','sympathetic-chain--1','sympathetic-chain-1'],'body',1.12)},
 {id:'peripheral-nerves',...L(['9 · เครือข่ายประสาทแขนและขา','9 · Peripheral nerves of the limbs'],['brachial, lumbar และ sacral plexuses กระจายเป็นเส้นประสาทหลัก เช่น radial, median, ulnar, femoral, sciatic และ tibial เพื่อเชื่อมสมอง/ไขสันหลังกับแขนขา','The brachial, lumbar and sacral plexuses give rise to major nerves such as radial, median, ulnar, femoral, sciatic and tibial nerves linking the CNS with the limbs.'],['brachial-plexus-1','radial-nerve-1','median-nerve-1','ulnar-nerve-1','lumbar-plexus-1','sacral-plexus-1','femoral-nerve-1','sciatic-nerve-1','tibial-nerve-1','common-fibular-nerve-1'],'body',1.08)}
);

lessons.sensory.steps.push(
 {id:'eye-components',...L(['7 · แสงผ่านส่วนประกอบของตา','7 · Light through the eye'],['แสงผ่าน cornea และ pupil จากนั้น lens ช่วยโฟกัสลงบน retina ซึ่งเปลี่ยนแสงเป็นสัญญาณและส่งต่อทาง optic nerve','Light passes through the cornea and pupil; the lens focuses it onto the retina, which converts light into signals carried by the optic nerve.'],['cornea-1','iris-1','lens-1','retina-1','optic-nerve-1'],'head',1.65)},
 {id:'middle-inner-ear',...L(['8 · จากแก้วหูสู่คอเคลีย','8 · From eardrum to cochlea'],['แก้วหูสั่นและถ่ายทอดแรงผ่าน malleus, incus และ stapes เข้าสู่ cochlea เพื่อเปลี่ยนการสั่นเป็นสัญญาณประสาท','The tympanic membrane vibrates and transmits force through the malleus, incus and stapes to the cochlea, where vibration becomes neural signals.'],['tympanic-membrane-1','malleus-1','incus-1','stapes-1','cochlea-1','vestibulocochlear-nerve-1'],'head',1.65)},
 {id:'balance',...L(['9 · หูชั้นในและการทรงตัว','9 · Inner ear and balance'],['semicircular canals ตรวจจับการหมุน ส่วน vestibule ตรวจจับความเร่งและตำแหน่งศีรษะ ช่วยให้สมองควบคุมสมดุล','The semicircular canals detect rotation and the vestibule senses linear acceleration and head position, supporting balance.'],['semicircular-canals--1','semicircular-canals-1','vestibule--1','vestibule-1','vestibulocochlear-nerve--1','vestibulocochlear-nerve-1'],'head',1.5)},
 {id:'chemical-senses',...L(['10 · กลิ่นและรส','10 · Smell and taste'],['เยื่อบุรับกลิ่นส่งสัญญาณไป olfactory bulbs ส่วน taste buds บนลิ้นตอบสนองต่อสารเคมีในอาหาร ทั้งสองระบบส่งข้อมูลเข้าสู่สมอง','The olfactory epithelium signals the olfactory bulbs, while taste buds on the tongue respond to food chemicals; both relay information to the brain.'],['olfactory-epithelium--1','olfactory-epithelium-1','olfactory-bulb--1','olfactory-bulb-1','taste-buds','tongue','brain'],'head',1.38)}
);

export const lessonOrder=['circulation','respiratory','digestive','nervous','urinary','skeletal','muscular','endocrine','lymphatic','reproductive','sensory','integumentary'];
export const circulationLessonSteps=lessons.circulation.steps;
export function getLesson(id){return lessons[id]||null;}
export function lessonStepAt(lessonOrIndex,index){
 const lesson=typeof lessonOrIndex==='string'?getLesson(lessonOrIndex):lessons.circulation;
 const i=typeof lessonOrIndex==='string'?index:lessonOrIndex;
 if(!lesson)return null;
 const n=lesson.steps.length;
 return lesson.steps[Math.max(0,Math.min(n-1,Number(i)||0))];
}
